//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INFOMAX.DB_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class infomaxEntities : DbContext
    {
        public infomaxEntities()
            : base("name=infomaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PageMetaDetail> PageMetaDetails { get; set; }
        public virtual DbSet<service> services { get; set; }
    }
}
