//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INFOMAX.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageMetaDetail
    {
        public int ID { get; set; }
        public string PageUrl { get; set; }
        public string Title { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string Maillink { get; set; }
        public string Fblink { get; set; }
        public string twlink { get; set; }
        public string iglink { get; set; }
        public string ytlink { get; set; }
        public string flrlink { get; set; }
        public string wplink { get; set; }
        public string prlink { get; set; }
        public string lnlink { get; set; }
        public string copytext { get; set; }
    }
}
