//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INFOMAX.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int Page_ID { get; set; }
        public string Page1 { get; set; }
    }
}
