//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INFOMAX.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FilePath { get; set; }
        public string P_Desc { get; set; }
        public string p_Features { get; set; }
        public string P_Price { get; set; }
    }
}
