//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INFOMAX.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int S_ID { get; set; }
        public string S_Title { get; set; }
        public string Ser_Desc { get; set; }
        public string Image { get; set; }
    }
}
